name: Docker Image CD

on:
  push:
    branches:
      - main
    paths:
      - 'Makefile'
      - 'Dockerfile'
      - '.github/workflows/docker.yml'

jobs:
  build:
    strategy:
      matrix:
        node-version: [ 16.1, 15.5 ]
        base_distro: [ bullseye, alpine, bookworm ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: list files
        id: list
        run: ls -la
      - name: set up permissions
        id: permissions
        run: chmod +X build.sh
      - name: Build and push
        id: docker_build_alpine
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          DOCKERFILE: ${{ github.workspace }}/alpine.Dockerfile
          NODE_VERSION: ${{ matrix.node-version }}
          BASE_IMAGE_DISTRO: ${{ matrix.base_distro }}
        if: ${{ matrix.base_distro == 'alpine' }}
        run: make --directory=${{ github.workspace }}/  deploy
