name: Docker Image CD

on:
  push:
    branches:
      - main
    paths:
      - 'Makefile'
      - 'Dockerfile'
      - '.github/workflows/docker.yml'
      - '*/Dockerfile'

jobs:
  build:
    strategy:
      matrix:
        PG_VARS: [ { Version: 16.1, BASE_DISTRO: alpine }, { Version: 15.5, BASE_DISTRO: bookworm } ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        id: docker_build_alpine
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          BASE_IMAGE_DISTRO:  ${{ matrix.PG_VARS.BASE_DISTRO }}
          PG_CONTAINER_VERSION: ${{ matrix.PG_VARS.Version }}
        run: make --directory=${{ github.workspace }}/  deploy
